quarkus:
  rest-client:
    org.lunskra.menu.MenuApiClient:
      url: "http://localhost:8088"
  cache:
    caffeine:
      expire-after-write: PT10S
  redis:
    logins:
      hosts: redis://localhost:6379/0